name: Deployment Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Make gradlew executable
        run: |
          cd TP1  
          chmod +x gradlew

      - name: Install dependencies
        run: |
          cd TP1  
          ./gradlew build 

      - name: Run tests
        run: |
          cd TP1  
          ./gradlew test  